/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.moduloSuscripcion;

import vistas.moduloCuenta.*;
import vistas.moduloServicioStreaming.*;
import vistas.moduloCliente.*;
import java.awt.Color;
import java.awt.Font;
import vistas.principal.GUIMenuPrincipal;

/**
 *
 * @author Alexander
 */
public class GUIModuloSuscripcion extends javax.swing.JFrame {

    /**
     * Creates new form GUIModuloCliente
     */
    public GUIModuloSuscripcion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneModuloSuscripcion = new javax.swing.JPanel();
        dsktModuloSuscripcion = new javax.swing.JDesktopPane();
        lblSuscripcionesCaducadas = new javax.swing.JLabel();
        lblGenerarSuscripcion = new javax.swing.JLabel();
        lblSuscripcionesPorCaducar = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        lblFondoModuloServcioStreaming = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPaneModuloSuscripcion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout dsktModuloSuscripcionLayout = new javax.swing.GroupLayout(dsktModuloSuscripcion);
        dsktModuloSuscripcion.setLayout(dsktModuloSuscripcionLayout);
        dsktModuloSuscripcionLayout.setHorizontalGroup(
            dsktModuloSuscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        dsktModuloSuscripcionLayout.setVerticalGroup(
            dsktModuloSuscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPaneModuloSuscripcion.add(dsktModuloSuscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 800, 580));

        lblSuscripcionesCaducadas.setBackground(new java.awt.Color(255, 255, 255));
        lblSuscripcionesCaducadas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSuscripcionesCaducadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSuscripcionesCaducadas.setText("Suscripciones caducadas");
        lblSuscripcionesCaducadas.setToolTipText("");
        lblSuscripcionesCaducadas.setOpaque(true);
        lblSuscripcionesCaducadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSuscripcionesCaducadasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSuscripcionesCaducadasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSuscripcionesCaducadasMouseExited(evt);
            }
        });
        jPaneModuloSuscripcion.add(lblSuscripcionesCaducadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 300, 50));

        lblGenerarSuscripcion.setBackground(new java.awt.Color(255, 255, 255));
        lblGenerarSuscripcion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblGenerarSuscripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGenerarSuscripcion.setText("Generar suscripción");
        lblGenerarSuscripcion.setOpaque(true);
        lblGenerarSuscripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGenerarSuscripcionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGenerarSuscripcionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGenerarSuscripcionMouseExited(evt);
            }
        });
        jPaneModuloSuscripcion.add(lblGenerarSuscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 300, 50));

        lblSuscripcionesPorCaducar.setBackground(new java.awt.Color(255, 255, 255));
        lblSuscripcionesPorCaducar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSuscripcionesPorCaducar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSuscripcionesPorCaducar.setText("Suscripciones por caducar");
        lblSuscripcionesPorCaducar.setOpaque(true);
        lblSuscripcionesPorCaducar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSuscripcionesPorCaducarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSuscripcionesPorCaducarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSuscripcionesPorCaducarMouseExited(evt);
            }
        });
        jPaneModuloSuscripcion.add(lblSuscripcionesPorCaducar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 300, 50));

        lblSalir.setBackground(new java.awt.Color(255, 255, 255));
        lblSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setText("Salir al menú principal");
        lblSalir.setOpaque(true);
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });
        jPaneModuloSuscripcion.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 300, 50));

        lblFondoModuloServcioStreaming.setBackground(new java.awt.Color(204, 204, 204));
        lblFondoModuloServcioStreaming.setOpaque(true);
        jPaneModuloSuscripcion.add(lblFondoModuloServcioStreaming, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneModuloSuscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneModuloSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblGenerarSuscripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenerarSuscripcionMouseClicked
        // TODO add your handling code here:
        this.dsktModuloSuscripcion.removeAll();
        GUIGenerarSuscripcion gui = new GUIGenerarSuscripcion();
        dsktModuloSuscripcion.add(gui);
        gui.setVisible(true);
    }//GEN-LAST:event_lblGenerarSuscripcionMouseClicked

    private void lblGenerarSuscripcionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenerarSuscripcionMouseEntered
        // TODO add your handling code here:
        lblGenerarSuscripcion.setBackground(new Color(220, 164, 25));
    }//GEN-LAST:event_lblGenerarSuscripcionMouseEntered

    private void lblGenerarSuscripcionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenerarSuscripcionMouseExited
        // TODO add your handling code here:
        lblGenerarSuscripcion.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblGenerarSuscripcionMouseExited

    private void lblSuscripcionesCaducadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuscripcionesCaducadasMouseClicked
        // TODO add your handling code here:
        this.dsktModuloSuscripcion.removeAll();
        GUISuscripcionesCaducadas gui = new GUISuscripcionesCaducadas();
        dsktModuloSuscripcion.add(gui);
        gui.setVisible(true);
    }//GEN-LAST:event_lblSuscripcionesCaducadasMouseClicked

    private void lblSuscripcionesCaducadasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuscripcionesCaducadasMouseExited
        // TODO add your handling code here:
        lblSuscripcionesCaducadas.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblSuscripcionesCaducadasMouseExited

    private void lblSuscripcionesCaducadasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuscripcionesCaducadasMouseEntered
        // TODO add your handling code here:
        lblSuscripcionesCaducadas.setBackground(new Color(220, 164, 25));
    }//GEN-LAST:event_lblSuscripcionesCaducadasMouseEntered

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        // TODO add your handling code here:
        GUIMenuPrincipal guiPrincipal = new GUIMenuPrincipal();
        this.setVisible(false);
        guiPrincipal.setVisible(true);
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseEntered
        // TODO add your handling code here:
        lblSalir.setBackground(new Color(220, 164, 25));
    }//GEN-LAST:event_lblSalirMouseEntered

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        // TODO add your handling code here:
        lblSalir.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblSalirMouseExited

    private void lblSuscripcionesPorCaducarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuscripcionesPorCaducarMouseClicked
        // TODO add your handling code here:
        this.dsktModuloSuscripcion.removeAll();
        GUISuscripcionesPorCaducar gui = new GUISuscripcionesPorCaducar();
        dsktModuloSuscripcion.add(gui);
        gui.setVisible(true);
    }//GEN-LAST:event_lblSuscripcionesPorCaducarMouseClicked

    private void lblSuscripcionesPorCaducarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuscripcionesPorCaducarMouseEntered
        // TODO add your handling code here:
        lblSuscripcionesPorCaducar.setBackground(new Color(220, 164, 25));
    }//GEN-LAST:event_lblSuscripcionesPorCaducarMouseEntered

    private void lblSuscripcionesPorCaducarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuscripcionesPorCaducarMouseExited
        // TODO add your handling code here:
        lblSuscripcionesPorCaducar.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblSuscripcionesPorCaducarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dsktModuloSuscripcion;
    private javax.swing.JPanel jPaneModuloSuscripcion;
    private javax.swing.JLabel lblFondoModuloServcioStreaming;
    private javax.swing.JLabel lblGenerarSuscripcion;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblSuscripcionesCaducadas;
    private javax.swing.JLabel lblSuscripcionesPorCaducar;
    // End of variables declaration//GEN-END:variables
}
