/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.moduloSuscripcion;

import vistas.moduloServicioStreaming.*;
import vistas.moduloCliente.*;
import controladores.*;
import entidades.*;
import excepcionesPropias.DatoNoValido;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexander
 */
public class GUISuscripcionesCaducadas extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIRegistrar
     */
    
    TipoServicioStreaming servicioStreamingPorEliminar = new TipoServicioStreaming();
    
    private void limpiar(){
        
    }
    
    private void configurarEncabezadoJTable(){
        jTableSuscripciones.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 14));
        jTableSuscripciones.getTableHeader().setOpaque(false);
        jTableSuscripciones.getTableHeader().setForeground(Color.BLACK);
        
    }
    
    private void llenarJTableSuscripciones(){
        DefaultTableModel dtm = new DefaultTableModel();
        
         ControladorSuscripcion controlador = new ControladorSuscripcion();
        ArrayList<Suscripcion> suscripciones = new ArrayList<>();
        try {
            suscripciones = controlador.obtenerSuscripcionesCaducadas();
        } catch (SQLException ex) {
            Logger.getLogger(GUISuscripcionesCaducadas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String[] cabecera = {"ID Suscripcion", "Cliente", "Plataforma", "Correo cuenta", "Fecha inicio", "Vencimiento"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataSuscripciones = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < suscripciones.size(); i++) {
            dataSuscripciones[0] = suscripciones.get(i).getSucripcionID();
            dataSuscripciones[1] = suscripciones.get(i).getNombreCliente();
            dataSuscripciones[2] = suscripciones.get(i).getPlataformaStreamingAsociada();
            dataSuscripciones[3] = suscripciones.get(i).getCorreoCuentaAsociada();
            dataSuscripciones[4] = suscripciones.get(i).getFechaInicio();
            dataSuscripciones[5] = suscripciones.get(i).getFechaFin();
            dtm.addRow(dataSuscripciones);
        }
        jTableSuscripciones.setModel(dtm);
    }
    
    private void establecerPorDefecto(){
        //cargarCodigo();
        llenarJTableSuscripciones();
    }
    
    public GUISuscripcionesCaducadas() {
        initComponents();
        establecerPorDefecto();
        configurarEncabezadoJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneSuscripcionesCaducadas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnProcesar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSuscripciones = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 153));

        jPaneSuscripcionesCaducadas.setBackground(new java.awt.Color(255, 255, 153));
        jPaneSuscripcionesCaducadas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Suscripciones caducadas");
        jPaneSuscripcionesCaducadas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 10, 700, -1));

        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPaneSuscripcionesCaducadas.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 140, 50));

        btnProcesar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnProcesar.setText("Procesar");
        btnProcesar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProcesarMouseClicked(evt);
            }
        });
        jPaneSuscripcionesCaducadas.add(btnProcesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 150, 50));

        jTableSuscripciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableSuscripciones.setFocusable(false);
        jTableSuscripciones.setGridColor(new java.awt.Color(0, 0, 0));
        jTableSuscripciones.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableSuscripciones.setRowHeight(20);
        jTableSuscripciones.setShowGrid(true);
        jTableSuscripciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSuscripcionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSuscripciones);

        jPaneSuscripcionesCaducadas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 770, 260));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setText("Pulsar el botón \"Procesar\" para modificar el estado de las suscripciones a inactivas");
        jPaneSuscripcionesCaducadas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneSuscripcionesCaducadas, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneSuscripcionesCaducadas, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcesarMouseClicked
        // TODO add your handling code here:
        try {
            
            ControladorSuscripcion controlador = new ControladorSuscripcion();
            ArrayList<Suscripcion> suscripciones = controlador.obtenerSuscripcionesCaducadas();
            
            for(int i = 0; i < suscripciones.size(); i++){
                controlador.actualizarEstadoSuscripcion(suscripciones.get(i).getSucripcionID());
            }
            
            JOptionPane.showMessageDialog(this, "Se han realizado cambios en el sistema.");
            
            establecerPorDefecto();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un número ENTERO.");
        }
    }//GEN-LAST:event_btnProcesarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void jTableSuscripcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSuscripcionesMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = 0;
        
        if(jTableSuscripciones.getSelectedRow() != -1){
            filaSeleccionada = jTableSuscripciones.getSelectedRow();
            
            //Solo el código
            servicioStreamingPorEliminar.setTipoServicioId(Integer.parseInt(jTableSuscripciones.getValueAt(filaSeleccionada, 0) + ""));
            servicioStreamingPorEliminar.setNombre(jTableSuscripciones.getValueAt(filaSeleccionada, 1) + "");
        }
    }//GEN-LAST:event_jTableSuscripcionesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPaneSuscripcionesCaducadas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSuscripciones;
    // End of variables declaration//GEN-END:variables
}
