/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.moduloCuenta;

import vistas.moduloServicioStreaming.*;
import vistas.moduloCliente.*;
import java.awt.Color;
import java.awt.Font;
import vistas.principal.GUIMenuPrincipal;

/**
 *
 * @author Alexander
 */
public class GUIModuloCuenta extends javax.swing.JFrame {

    /**
     * Creates new form GUIModuloCliente
     */
    public GUIModuloCuenta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneModuloCuenta = new javax.swing.JPanel();
        dsktModuloCuentas = new javax.swing.JDesktopPane();
        lblVisualizar = new javax.swing.JLabel();
        lblRegistrarCuenta = new javax.swing.JLabel();
        lblActualizarCuenta = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        lblFondoModuloServcioStreaming = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPaneModuloCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout dsktModuloCuentasLayout = new javax.swing.GroupLayout(dsktModuloCuentas);
        dsktModuloCuentas.setLayout(dsktModuloCuentasLayout);
        dsktModuloCuentasLayout.setHorizontalGroup(
            dsktModuloCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        dsktModuloCuentasLayout.setVerticalGroup(
            dsktModuloCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPaneModuloCuenta.add(dsktModuloCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 800, 580));

        lblVisualizar.setBackground(new java.awt.Color(255, 255, 255));
        lblVisualizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblVisualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVisualizar.setText("Visualizar cuentas");
        lblVisualizar.setToolTipText("");
        lblVisualizar.setOpaque(true);
        lblVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVisualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVisualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVisualizarMouseExited(evt);
            }
        });
        jPaneModuloCuenta.add(lblVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 300, 50));

        lblRegistrarCuenta.setBackground(new java.awt.Color(255, 255, 255));
        lblRegistrarCuenta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRegistrarCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrarCuenta.setText("Registro de cuenta");
        lblRegistrarCuenta.setOpaque(true);
        lblRegistrarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarCuentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistrarCuentaMouseExited(evt);
            }
        });
        jPaneModuloCuenta.add(lblRegistrarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 300, 50));

        lblActualizarCuenta.setBackground(new java.awt.Color(255, 255, 255));
        lblActualizarCuenta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblActualizarCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActualizarCuenta.setText("Actualización de cuenta");
        lblActualizarCuenta.setOpaque(true);
        lblActualizarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblActualizarCuentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblActualizarCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblActualizarCuentaMouseExited(evt);
            }
        });
        jPaneModuloCuenta.add(lblActualizarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 300, 50));

        lblSalir.setBackground(new java.awt.Color(255, 255, 255));
        lblSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setText("Salir al menú principal");
        lblSalir.setOpaque(true);
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });
        jPaneModuloCuenta.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 300, 50));

        lblFondoModuloServcioStreaming.setBackground(new java.awt.Color(204, 204, 204));
        lblFondoModuloServcioStreaming.setOpaque(true);
        jPaneModuloCuenta.add(lblFondoModuloServcioStreaming, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneModuloCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneModuloCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegistrarCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarCuentaMouseClicked
        // TODO add your handling code here:
        this.dsktModuloCuentas.removeAll();
        GUIRegistrarCuenta guiRegistro = new GUIRegistrarCuenta();
        dsktModuloCuentas.add(guiRegistro);
        guiRegistro.setVisible(true);
    }//GEN-LAST:event_lblRegistrarCuentaMouseClicked

    private void lblRegistrarCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarCuentaMouseEntered
        // TODO add your handling code here:
        lblRegistrarCuenta.setBackground(new Color(220, 164, 25));
    }//GEN-LAST:event_lblRegistrarCuentaMouseEntered

    private void lblRegistrarCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarCuentaMouseExited
        // TODO add your handling code here:
        lblRegistrarCuenta.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblRegistrarCuentaMouseExited

    private void lblVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisualizarMouseClicked
        // TODO add your handling code here:
        this.dsktModuloCuentas.removeAll();
        GUIReporteCuentas gui = new GUIReporteCuentas();
        dsktModuloCuentas.add(gui);
        gui.setVisible(true);
    }//GEN-LAST:event_lblVisualizarMouseClicked

    private void lblVisualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisualizarMouseExited
        // TODO add your handling code here:
        lblVisualizar.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblVisualizarMouseExited

    private void lblVisualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisualizarMouseEntered
        // TODO add your handling code here:
        lblVisualizar.setBackground(new Color(220, 164, 25));
    }//GEN-LAST:event_lblVisualizarMouseEntered

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        // TODO add your handling code here:
        GUIMenuPrincipal guiPrincipal = new GUIMenuPrincipal();
        this.setVisible(false);
        guiPrincipal.setVisible(true);
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseEntered
        // TODO add your handling code here:
        lblSalir.setBackground(new Color(220, 164, 25));
    }//GEN-LAST:event_lblSalirMouseEntered

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        // TODO add your handling code here:
        lblSalir.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblSalirMouseExited

    private void lblActualizarCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarCuentaMouseClicked
        // TODO add your handling code here:
        this.dsktModuloCuentas.removeAll();
        GUIActualizarCuenta gui = new GUIActualizarCuenta();
        dsktModuloCuentas.add(gui);
        gui.setVisible(true);
    }//GEN-LAST:event_lblActualizarCuentaMouseClicked

    private void lblActualizarCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarCuentaMouseEntered
        // TODO add your handling code here:
        lblActualizarCuenta.setBackground(new Color(220, 164, 25));
    }//GEN-LAST:event_lblActualizarCuentaMouseEntered

    private void lblActualizarCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarCuentaMouseExited
        // TODO add your handling code here:
        lblActualizarCuenta.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblActualizarCuentaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dsktModuloCuentas;
    private javax.swing.JPanel jPaneModuloCuenta;
    private javax.swing.JLabel lblActualizarCuenta;
    private javax.swing.JLabel lblFondoModuloServcioStreaming;
    private javax.swing.JLabel lblRegistrarCuenta;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblVisualizar;
    // End of variables declaration//GEN-END:variables
}
