/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.moduloCuenta;

import vistas.moduloServicioStreaming.*;
import vistas.moduloCliente.*;
import controladores.ControladorCliente;
import controladores.*;
import entidades.*;
import excepcionesPropias.DatoNoValido;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexander
 */
public class GUIReporteCuentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIRegistrar
     */
    
    private void limpiar(){
        txtBusquedaCorreo.setText("");
    }
    
    private void configurarEncabezadoJTable(){
        jTableCuentas.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 14));
        jTableCuentas.getTableHeader().setOpaque(false);
        jTableCuentas.getTableHeader().setForeground(Color.BLACK);
        
    }
    
    private void llenarJTableCuentas(){
        DefaultTableModel dtm = new DefaultTableModel();
        
        ControladorCuenta controladorCuenta = new ControladorCuenta();
        ArrayList<Cuenta> cuentas = new ArrayList<>();
        
        try {
            cuentas = controladorCuenta.obtenerCuentas();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un problema al cargar los datos.");
        }
        
        String[] cabecera = {"ID cuenta", "Correo", "Contrasena", "Nº actual de usuarios"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataCuentas = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < cuentas.size(); i++) {
            dataCuentas[0] = cuentas.get(i).getCuentaId();
            dataCuentas[1] = cuentas.get(i).getCorreo();
            dataCuentas[2] = cuentas.get(i).getContrasena();
            dataCuentas[3] = cuentas.get(i).getNumActualUsuarios();
            dtm.addRow(dataCuentas);
        }
        jTableCuentas.setModel(dtm);
    }
    
    private void llenarJTableCuentas(ArrayList<Cuenta> cuentas){
        DefaultTableModel dtm = new DefaultTableModel();
        
        String[] cabecera = {"ID cuenta", "Correo", "Contrasena", "Nº actual de usuarios"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataCuentas = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < cuentas.size(); i++) {
            dataCuentas[0] = cuentas.get(i).getCuentaId();
            dataCuentas[1] = cuentas.get(i).getCorreo();
            dataCuentas[2] = cuentas.get(i).getContrasena();
            dataCuentas[3] = cuentas.get(i).getNumActualUsuarios();
            dtm.addRow(dataCuentas);
        }
        jTableCuentas.setModel(dtm);
    }
    
    private void establecerPorDefecto(){
        //cargarCodigo();
        limpiar();
        txtBusquedaCorreo.setFocusable(true);
        llenarJTableCuentas();
        
    }
    
    public GUIReporteCuentas() {
        initComponents();
        establecerPorDefecto();
        configurarEncabezadoJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneReporte = new javax.swing.JPanel();
        txtBusquedaCorreo = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCuentas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jPaneReporte.setBackground(new java.awt.Color(255, 255, 255));
        jPaneReporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusquedaCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaCorreoKeyPressed(evt);
            }
        });
        jPaneReporte.add(txtBusquedaCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 250, -1));

        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPaneReporte.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 140, 50));

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Buscar correo electrónico de la cuenta:");
        jPaneReporte.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, -1));

        jTableCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCuentas.setFocusable(false);
        jTableCuentas.setGridColor(new java.awt.Color(0, 0, 0));
        jTableCuentas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableCuentas.setRowHeight(20);
        jTableCuentas.setShowGrid(true);
        jScrollPane1.setViewportView(jTableCuentas);

        jPaneReporte.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 780, 310));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Reporte de cuentas");
        jPaneReporte.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void txtBusquedaCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaCorreoKeyPressed
        // TODO add your handling code here:

        try {
            ControladorCuenta controladorCuenta = new ControladorCuenta();
            llenarJTableCuentas(controladorCuenta.obtenerCuentas(txtBusquedaCorreo.getText().trim()));
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_txtBusquedaCorreoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPaneReporte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCuentas;
    private javax.swing.JTextField txtBusquedaCorreo;
    // End of variables declaration//GEN-END:variables
}
