/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.moduloCuenta;

import vistas.moduloServicioStreaming.*;
import controladores.*;
import entidades.*;
import excepcionesPropias.DatoNoValido;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexander
 */
public class GUIRegistrarCuenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIRegistrar
     */
    
    private void cargarCodigo(){
        ControladorCuenta controlador = new ControladorCuenta();
        try {
            lblCodigo.setText(controlador.obtenerNuevoCodigo()+ "");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void limpiar(){
        txtCorreo.setText("");
        txtContrasena.setText("");
    }
    
    private void cargarCboPlataformas(){
        ControladorServicioStreaming controlador = new ControladorServicioStreaming();
        ArrayList<TipoServicioStreaming> plataformas;
        try {
            plataformas = controlador.obtenerServiciosStreaming();
            plataformas = controlador.ordenarTipoServiciosXNombreAsc(plataformas);
            for (int i = 0; i < plataformas.size(); i++) {
                cboPlataformas.addItem(plataformas.get(i).getTipoServicioId() + " - " + plataformas.get(i).getNombre());
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUIRegistrarCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void cargarCboPlanes(int plataformaId){
        cboPlanes.removeAllItems();
        ControladorServicioStreaming controlador = new ControladorServicioStreaming();
        ArrayList<Plan> planes;
        try {
            planes = controlador.obtenerPlanes(plataformaId);
            for (int i = 0; i < planes.size(); i++) {
                cboPlanes.addItem(planes.get(i).getPlanId()+ " - Plan de " + planes.get(i).getTiempoMeses() + " mes(es)");
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUIRegistrarCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void establecerPorDefecto(){
        cargarCodigo();
        cargarCboPlataformas();
        limpiar();
        txtCorreo.setFocusable(true);
    }
    
    public GUIRegistrarCuenta() {
        initComponents();
        establecerPorDefecto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneRegistrarPlan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cboPlataformas = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cboPlanes = new javax.swing.JComboBox<>();

        jPaneRegistrarPlan.setBackground(new java.awt.Color(255, 255, 255));
        jPaneRegistrarPlan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generar cuenta de usuario");
        jPaneRegistrarPlan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 680, -1));

        lblCodigo.setBackground(new java.awt.Color(204, 204, 204));
        lblCodigo.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCodigo.setOpaque(true);
        jPaneRegistrarPlan.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 180, 20));

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Correo electrónico de la cuenta:");
        jPaneRegistrarPlan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 250, -1));

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Contraseña:");
        jPaneRegistrarPlan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 210, -1));

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Seleccionar plataforma de streaming:");
        jPaneRegistrarPlan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 260, -1));
        jPaneRegistrarPlan.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 280, -1));
        jPaneRegistrarPlan.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 280, -1));

        btnRegistrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        jPaneRegistrarPlan.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 140, 50));

        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPaneRegistrarPlan.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 140, 50));

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Código (autogenerado) :");
        jPaneRegistrarPlan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 210, -1));

        cboPlataformas.setBackground(new java.awt.Color(204, 204, 204));
        cboPlataformas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPlataformasItemStateChanged(evt);
            }
        });
        jPaneRegistrarPlan.add(cboPlataformas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 230, -1));

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Seleccionar plan:");
        jPaneRegistrarPlan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 260, -1));

        cboPlanes.setBackground(new java.awt.Color(204, 204, 204));
        jPaneRegistrarPlan.add(cboPlanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneRegistrarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneRegistrarPlan, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
        try {
            if(txtCorreo.getText().equals("") || txtContrasena.getText().equals("") || cboPlanes.getSelectedIndex() == -1){
                throw new DatoNoValido("Debe seleccionar e ingresar datos en todos los campos.");
            }
            
            Cuenta objCuenta = new Cuenta();
            ControladorCuenta controlador = new ControladorCuenta();

            String itemPlanes[] = cboPlanes.getSelectedItem().toString().split("-");
            
            objCuenta.setPlanId(Integer.parseInt(itemPlanes[0].trim()));
            objCuenta.setCorreo(txtCorreo.getText().trim());
            objCuenta.setContrasena(txtContrasena.getText().trim());

            controlador.registrar(objCuenta);

            JOptionPane.showMessageDialog(this, "Nueva cuenta registrada al sistema.");

            establecerPorDefecto();
        } catch (DatoNoValido | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void cboPlataformasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPlataformasItemStateChanged
        // TODO add your handling code here:
        if(cboPlataformas.getSelectedIndex() != -1){
            String item[] = cboPlataformas.getSelectedItem().toString().split("-");
            int planId = Integer.parseInt(item[0].trim());
            cargarCboPlanes(planId);
        }
    }//GEN-LAST:event_cboPlataformasItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboPlanes;
    private javax.swing.JComboBox<String> cboPlataformas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPaneRegistrarPlan;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
