/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.principal;

import vistas.moduloCliente.*;
import vistas.moduloCuenta.GUIModuloCuenta;
import vistas.moduloServicioStreaming.GUIModuloServicioStreaming;
import vistas.moduloSuscripcion.GUIModuloSuscripcion;

/**
 *
 * @author Alexander
 */
public class GUIMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenuPrincipal
     */
    int xMouse, yMouse;
    
    public GUIMenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneMenuPrincipal = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        btnServiciosStreaming = new javax.swing.JButton();
        btnCuentasUsuario = new javax.swing.JButton();
        btnSuscripciones = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPaneMenuPrincipal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPaneMenuPrincipalMouseDragged(evt);
            }
        });
        jPaneMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPaneMenuPrincipalMousePressed(evt);
            }
        });
        jPaneMenuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Clientes.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
        });
        jPaneMenuPrincipal.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 300, 50));

        btnServiciosStreaming.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnServiciosStreaming.setText("Servicios Streaming");
        btnServiciosStreaming.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnServiciosStreamingMouseClicked(evt);
            }
        });
        jPaneMenuPrincipal.add(btnServiciosStreaming, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 300, 50));

        btnCuentasUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnCuentasUsuario.setText("Gestión de cuentas de usuario");
        btnCuentasUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCuentasUsuarioMouseClicked(evt);
            }
        });
        jPaneMenuPrincipal.add(btnCuentasUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 300, 50));

        btnSuscripciones.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnSuscripciones.setText("Suscripciones");
        btnSuscripciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuscripcionesMouseClicked(evt);
            }
        });
        jPaneMenuPrincipal.add(btnSuscripciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 300, 50));

        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPaneMenuPrincipal.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 160, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portada_menuPrinicpal.jpeg"))); // NOI18N
        jPaneMenuPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 0, 338, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portada2_MenuPrincipal.jpg"))); // NOI18N
        jPaneMenuPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        // TODO add your handling code here:
        GUIModuloCliente guiClientes = new GUIModuloCliente();
        this.setVisible(false);
        guiClientes.setVisible(true);
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnServiciosStreamingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServiciosStreamingMouseClicked
        // TODO add your handling code here:
        GUIModuloServicioStreaming gui = new GUIModuloServicioStreaming();
        this.setVisible(false);
        gui.setVisible(true);

    }//GEN-LAST:event_btnServiciosStreamingMouseClicked

    private void btnCuentasUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuentasUsuarioMouseClicked
        // TODO add your handling code here:
        GUIModuloCuenta guiClientes = new GUIModuloCuenta();
        this.setVisible(false);
        guiClientes.setVisible(true);
    }//GEN-LAST:event_btnCuentasUsuarioMouseClicked

    private void btnSuscripcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuscripcionesMouseClicked
        // TODO add your handling code here:
        GUIModuloSuscripcion gui = new GUIModuloSuscripcion();
        this.setVisible(false);
        gui.setVisible(true);
    }//GEN-LAST:event_btnSuscripcionesMouseClicked

    private void jPaneMenuPrincipalMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaneMenuPrincipalMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPaneMenuPrincipalMouseDragged

    private void jPaneMenuPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaneMenuPrincipalMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPaneMenuPrincipalMousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnCuentasUsuario;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnServiciosStreaming;
    private javax.swing.JButton btnSuscripciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPaneMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
