/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.moduloCliente;

import controladores.ControladorCliente;
import entidades.Cliente;
import excepcionesPropias.DatoNoValido;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexander
 */
public class GUIActualizar extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIRegistrar
     */
    ControladorCliente controlador = new ControladorCliente();
    
    private void limpiar(){
        txtBusquedaCliente.setText("");
        lblCodigo.setText("");
        txtNombreCompleto.setText("");
        txtNombreUsuario.setText("");
        txtCelular.setText("");
    }
    
    private void configurarEncabezadoJTable(){
        jTableClientes.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 14));
        jTableClientes.getTableHeader().setOpaque(false);
        jTableClientes.getTableHeader().setForeground(Color.BLACK);
        
    }
    
    private void llenarJTableClientes(){
        DefaultTableModel dtm = new DefaultTableModel();
        
        ArrayList<Cliente> clientes = new ArrayList<>();
        
        try {
            clientes = controlador.obtenerClientes();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un problema al cargar los datos de clientes.");
        }
        
        String[] cabecera = {"Código", "Nombre completo", "Nombre de usuario", "Celular"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataCliente = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < clientes.size(); i++) {
            dataCliente[0] = clientes.get(i).getClienteId();
            dataCliente[1] = clientes.get(i).getNombreCompleto();
            dataCliente[2] = clientes.get(i).getNombreUsuario();
            dataCliente[3] = clientes.get(i).getCelular();
            dtm.addRow(dataCliente);
        }
        jTableClientes.setModel(dtm);
    }
    
    private void llenarJTableClientes(ArrayList<Cliente> clientes){
        DefaultTableModel dtm = new DefaultTableModel();
        
        String[] cabecera = {"Código", "Nombre completo", "Nombre de usuario", "Celular"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataCliente = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < clientes.size(); i++) {
            dataCliente[0] = clientes.get(i).getClienteId();
            dataCliente[1] = clientes.get(i).getNombreCompleto();
            dataCliente[2] = clientes.get(i).getNombreUsuario();
            dataCliente[3] = clientes.get(i).getCelular();
            dtm.addRow(dataCliente);
        }
        jTableClientes.setModel(dtm);
    }
    
    private void establecerPorDefecto(){
        //cargarCodigo();
        limpiar();
        txtBusquedaCliente.setFocusable(true);
        llenarJTableClientes();
    }
    
    public GUIActualizar() {
        initComponents();
        establecerPorDefecto();
        configurarEncabezadoJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneActualizar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        txtBusquedaCliente = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();

        jPaneActualizar.setBackground(new java.awt.Color(111, 159, 195));
        jPaneActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Actualización de clientes");
        jPaneActualizar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 10, 630, -1));

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Número de celular:");
        jPaneActualizar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 210, -1));

        lblCodigo.setBackground(new java.awt.Color(204, 204, 204));
        lblCodigo.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCodigo.setOpaque(true);
        jPaneActualizar.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 210, 20));

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nombre completo:");
        jPaneActualizar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 210, -1));

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nombre de usuario:");
        jPaneActualizar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 210, -1));

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Datos de cliente:");
        jPaneActualizar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 180, -1));
        jPaneActualizar.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 280, -1));

        txtBusquedaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaClienteKeyTyped(evt);
            }
        });
        jPaneActualizar.add(txtBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 280, -1));
        jPaneActualizar.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 280, -1));

        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPaneActualizar.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 140, 50));

        btnActualizar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        jPaneActualizar.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 140, 50));

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Código:");
        jPaneActualizar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 210, -1));
        jPaneActualizar.add(txtNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 280, -1));

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Buscar nombre de cliente:");
        jPaneActualizar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, -1));

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableClientes.setFocusable(false);
        jTableClientes.setGridColor(new java.awt.Color(0, 0, 0));
        jTableClientes.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableClientes.setRowHeight(20);
        jTableClientes.setShowGrid(true);
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        jPaneActualizar.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 770, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        // TODO add your handling code here:
        try {
            Cliente objCliente = new Cliente();

            objCliente.setClienteId(Integer.parseInt(lblCodigo.getText()));
            objCliente.setNombreCompleto(txtNombreCompleto.getText().trim());
            objCliente.setNombreUsuario(txtNombreUsuario.getText().trim());
            objCliente.setCelular(txtCelular.getText().trim());

            controlador.actualizar(objCliente);

            JOptionPane.showMessageDialog(this, String.format("Datos del cliente %s actualizados correctamente.", objCliente.getNombreCompleto()));

            establecerPorDefecto();
        } catch (DatoNoValido | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Asegúrese de seleccionar un registro de la tabla.");
        }
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void txtBusquedaClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaClienteKeyPressed
        // TODO add your handling code here:
        
        try {
            llenarJTableClientes(controlador.obtenerClientes(txtBusquedaCliente.getText().trim()));
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_txtBusquedaClienteKeyPressed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void txtBusquedaClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaClienteKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtBusquedaClienteKeyTyped

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = 0;
        
        if(jTableClientes.getSelectedRow() != -1){
            filaSeleccionada = jTableClientes.getSelectedRow();
            lblCodigo.setText(jTableClientes.getValueAt(filaSeleccionada, 0) + "");
            txtNombreCompleto.setText(jTableClientes.getValueAt(filaSeleccionada, 1) + "");
            txtNombreUsuario.setText(jTableClientes.getValueAt(filaSeleccionada, 2) + "");
            txtCelular.setText(jTableClientes.getValueAt(filaSeleccionada, 3) + "");
        }
    }//GEN-LAST:event_jTableClientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPaneActualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTextField txtBusquedaCliente;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
