/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.moduloCliente;

import controladores.ControladorCliente;
import entidades.Cliente;
import excepcionesPropias.DatoNoValido;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexander
 */
public class GUIEliminar extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIRegistrar
     */
    ControladorCliente controlador = new ControladorCliente();
    Cliente clientePorEliminar = new Cliente();
    
    private void limpiar(){
        txtBusquedaCliente.setText("");
    }
    
    private void configurarEncabezadoJTable(){
        jTableClientes.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 14));
        jTableClientes.getTableHeader().setOpaque(false);
        jTableClientes.getTableHeader().setForeground(Color.BLACK);
        
    }
    
    private void llenarJTableClientes(){
        DefaultTableModel dtm = new DefaultTableModel();
        
        ArrayList<Cliente> clientes = new ArrayList<>();
        
        try {
            clientes = controlador.obtenerClientes();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un problema al cargar los datos de clientes.");
        }
        
        String[] cabecera = {"Código", "Nombre completo", "Nombre de usuario", "Celular"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataCliente = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < clientes.size(); i++) {
            dataCliente[0] = clientes.get(i).getClienteId();
            dataCliente[1] = clientes.get(i).getNombreCompleto();
            dataCliente[2] = clientes.get(i).getNombreUsuario();
            dataCliente[3] = clientes.get(i).getCelular();
            dtm.addRow(dataCliente);
        }
        jTableClientes.setModel(dtm);
    }
    
    private void llenarJTableClientes(ArrayList<Cliente> clientes){
        DefaultTableModel dtm = new DefaultTableModel();
        
        String[] cabecera = {"Código", "Nombre completo", "Nombre de usuario", "Celular"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataCliente = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < clientes.size(); i++) {
            dataCliente[0] = clientes.get(i).getClienteId();
            dataCliente[1] = clientes.get(i).getNombreCompleto();
            dataCliente[2] = clientes.get(i).getNombreUsuario();
            dataCliente[3] = clientes.get(i).getCelular();
            dtm.addRow(dataCliente);
        }
        jTableClientes.setModel(dtm);
    }
    
    private void establecerPorDefecto(){
        //cargarCodigo();
        limpiar();
        txtBusquedaCliente.setFocusable(true);
        llenarJTableClientes();
    }
    
    public GUIEliminar() {
        initComponents();
        establecerPorDefecto();
        configurarEncabezadoJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneActualizar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBusquedaCliente = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();

        jPaneActualizar.setBackground(new java.awt.Color(111, 159, 195));
        jPaneActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eliminación de clientes");
        jPaneActualizar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 10, 630, -1));

        txtBusquedaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaClienteKeyTyped(evt);
            }
        });
        jPaneActualizar.add(txtBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 280, -1));

        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPaneActualizar.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 140, 50));

        btnEliminar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        jPaneActualizar.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 140, 50));

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Buscar nombre de cliente:");
        jPaneActualizar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, -1));

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableClientes.setFocusable(false);
        jTableClientes.setGridColor(new java.awt.Color(0, 0, 0));
        jTableClientes.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableClientes.setRowHeight(20);
        jTableClientes.setShowGrid(true);
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        jPaneActualizar.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 770, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        try {

            controlador.eliminar(clientePorEliminar);

            JOptionPane.showMessageDialog(this, String.format("Datos del cliente %s eliminados correctamente.", clientePorEliminar.getNombreCompleto()));

            establecerPorDefecto();
        } catch (DatoNoValido | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void txtBusquedaClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaClienteKeyPressed
        // TODO add your handling code here:
        
        try {
            llenarJTableClientes(controlador.obtenerClientes(txtBusquedaCliente.getText().trim()));
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_txtBusquedaClienteKeyPressed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void txtBusquedaClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaClienteKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtBusquedaClienteKeyTyped

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = 0;
        
        if(jTableClientes.getSelectedRow() != -1){
            filaSeleccionada = jTableClientes.getSelectedRow();
            clientePorEliminar.setClienteId(Integer.parseInt(jTableClientes.getValueAt(filaSeleccionada, 0) + ""));
            clientePorEliminar.setNombreCompleto((jTableClientes.getValueAt(filaSeleccionada, 1) + ""));
        }
    }//GEN-LAST:event_jTableClientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPaneActualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField txtBusquedaCliente;
    // End of variables declaration//GEN-END:variables
}
