/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.moduloCliente;

import java.awt.Color;
import java.awt.Font;
import vistas.principal.GUIMenuPrincipal;

/**
 *
 * @author Alexander
 */
public class GUIModuloCliente extends javax.swing.JFrame {

    /**
     * Creates new form GUIModuloCliente
     */
    public GUIModuloCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneModuloCliente = new javax.swing.JPanel();
        dsktModuloCliente = new javax.swing.JDesktopPane();
        lblReporteGeneral = new javax.swing.JLabel();
        lblInformeCliente = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        lblActualizar = new javax.swing.JLabel();
        lblRegistrar = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPaneModuloCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout dsktModuloClienteLayout = new javax.swing.GroupLayout(dsktModuloCliente);
        dsktModuloCliente.setLayout(dsktModuloClienteLayout);
        dsktModuloClienteLayout.setHorizontalGroup(
            dsktModuloClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        dsktModuloClienteLayout.setVerticalGroup(
            dsktModuloClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPaneModuloCliente.add(dsktModuloCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 800, 580));

        lblReporteGeneral.setBackground(new java.awt.Color(255, 255, 255));
        lblReporteGeneral.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblReporteGeneral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReporteGeneral.setText("Reporte general de clientes");
        lblReporteGeneral.setOpaque(true);
        lblReporteGeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReporteGeneralMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReporteGeneralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReporteGeneralMouseExited(evt);
            }
        });
        jPaneModuloCliente.add(lblReporteGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 280, 50));

        lblInformeCliente.setBackground(new java.awt.Color(255, 255, 255));
        lblInformeCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblInformeCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInformeCliente.setText("Informe detallado de cliente");
        lblInformeCliente.setOpaque(true);
        lblInformeCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInformeClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInformeClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInformeClienteMouseExited(evt);
            }
        });
        jPaneModuloCliente.add(lblInformeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 280, 50));

        lblEliminar.setBackground(new java.awt.Color(255, 255, 255));
        lblEliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminar.setText("Eliminación cliente");
        lblEliminar.setOpaque(true);
        lblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEliminarMouseExited(evt);
            }
        });
        jPaneModuloCliente.add(lblEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 280, 50));

        lblActualizar.setBackground(new java.awt.Color(255, 255, 255));
        lblActualizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActualizar.setText("Actualización de cliente");
        lblActualizar.setOpaque(true);
        lblActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblActualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblActualizarMouseExited(evt);
            }
        });
        jPaneModuloCliente.add(lblActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 280, 50));

        lblRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        lblRegistrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrar.setText("Registro de cliente");
        lblRegistrar.setOpaque(true);
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseExited(evt);
            }
        });
        jPaneModuloCliente.add(lblRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, 50));

        lblSalir.setBackground(new java.awt.Color(255, 255, 255));
        lblSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setText("Salir al menú principal");
        lblSalir.setOpaque(true);
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });
        jPaneModuloCliente.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 280, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_moduloClientes.jpg"))); // NOI18N
        jPaneModuloCliente.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneModuloCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneModuloCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked
        // TODO add your handling code here:
        this.dsktModuloCliente.removeAll();
        GUIRegistrar guiRegistro = new GUIRegistrar();
        dsktModuloCliente.add(guiRegistro);
        guiRegistro.setVisible(true);
    }//GEN-LAST:event_lblRegistrarMouseClicked

    private void lblRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseEntered
        // TODO add your handling code here:
        lblRegistrar.setBackground(new Color(182, 203, 224));
    }//GEN-LAST:event_lblRegistrarMouseEntered

    private void lblRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseExited
        // TODO add your handling code here:
        lblRegistrar.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblRegistrarMouseExited

    private void lblActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseClicked
        // TODO add your handling code here:
        this.dsktModuloCliente.removeAll();
        GUIActualizar gui = new GUIActualizar();
        dsktModuloCliente.add(gui);
        gui.setVisible(true);
    }//GEN-LAST:event_lblActualizarMouseClicked

    private void lblActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseExited
        // TODO add your handling code here:
        lblActualizar.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblActualizarMouseExited

    private void lblActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseEntered
        // TODO add your handling code here:
        lblActualizar.setBackground(new Color(182, 203, 224));
    }//GEN-LAST:event_lblActualizarMouseEntered

    private void lblEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseClicked
        // TODO add your handling code here:
        this.dsktModuloCliente.removeAll();
        GUIEliminar gui = new GUIEliminar();
        dsktModuloCliente.add(gui);
        gui.setVisible(true);
    }//GEN-LAST:event_lblEliminarMouseClicked

    private void lblEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseEntered
        // TODO add your handling code here:
        lblEliminar.setBackground(new Color(182, 203, 224));
    }//GEN-LAST:event_lblEliminarMouseEntered

    private void lblEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseExited
        // TODO add your handling code here:
        lblEliminar.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblEliminarMouseExited

    private void lblReporteGeneralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReporteGeneralMouseClicked
        // TODO add your handling code here:
        this.dsktModuloCliente.removeAll();
        GUIReporteGeneralClientes gui = new GUIReporteGeneralClientes();
        dsktModuloCliente.add(gui);
        gui.setVisible(true);
    }//GEN-LAST:event_lblReporteGeneralMouseClicked

    private void lblReporteGeneralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReporteGeneralMouseEntered
        // TODO add your handling code here:
        lblReporteGeneral.setBackground(new Color(182, 203, 224));
    }//GEN-LAST:event_lblReporteGeneralMouseEntered

    private void lblReporteGeneralMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReporteGeneralMouseExited
        // TODO add your handling code here:
        lblReporteGeneral.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblReporteGeneralMouseExited

    private void lblInformeClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInformeClienteMouseClicked
        // TODO add your handling code here:
        this.dsktModuloCliente.removeAll();
        GUIInformeCliente gui = new GUIInformeCliente();
        dsktModuloCliente.add(gui);
        gui.setVisible(true);
    }//GEN-LAST:event_lblInformeClienteMouseClicked

    private void lblInformeClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInformeClienteMouseEntered
        // TODO add your handling code here:
        lblInformeCliente.setBackground(new Color(182, 203, 224));
    }//GEN-LAST:event_lblInformeClienteMouseEntered

    private void lblInformeClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInformeClienteMouseExited
        // TODO add your handling code here:
        lblInformeCliente.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblInformeClienteMouseExited

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        // TODO add your handling code here:
        GUIMenuPrincipal guiPrincipal = new GUIMenuPrincipal();
        this.setVisible(false);
        guiPrincipal.setVisible(true);
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseEntered
        // TODO add your handling code here:
        lblSalir.setBackground(new Color(182, 203, 224));
    }//GEN-LAST:event_lblSalirMouseEntered

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        // TODO add your handling code here:
        lblSalir.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblSalirMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dsktModuloCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPaneModuloCliente;
    private javax.swing.JLabel lblActualizar;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblInformeCliente;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblReporteGeneral;
    private javax.swing.JLabel lblSalir;
    // End of variables declaration//GEN-END:variables
}
