/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.moduloCliente;

import controladores.ControladorCliente;
import entidades.Cliente;
import excepcionesPropias.DatoNoValido;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexander
 */
public class GUIReporteGeneralClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIRegistrar
     */
    ControladorCliente controlador = new ControladorCliente();
    ArrayList<Cliente> totalClientes;
    
    private void configurarRadioButtonOrden(){
        btnGroupOrdenar.add(rdbtnCantidadAscendente);
        btnGroupOrdenar.add(rdbtnCantidadDescendente);
        btnGroupOrdenar.add(rdbtnNombreAscendente);
        btnGroupOrdenar.add(rdbtnNombreDescendente);
    }
    
    private void configurarEncabezadoJTable(){
        jTableClientes.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 14));
        jTableClientes.getTableHeader().setOpaque(false);
        jTableClientes.getTableHeader().setForeground(Color.BLACK);
        
    }
    
    private void llenarJTableClientes(){
        DefaultTableModel dtm = new DefaultTableModel();
        
        try {
            totalClientes = controlador.obtenerClientes();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un problema al cargar los datos de clientes.");
        }
        
        String[] cabecera = {"Código", "Nombre completo", "Nombre de usuario", "Celular", "Nº suscripciones"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataCliente = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < totalClientes.size(); i++) {
            dataCliente[0] = totalClientes.get(i).getClienteId();
            dataCliente[1] = totalClientes.get(i).getNombreCompleto();
            dataCliente[2] = totalClientes.get(i).getNombreUsuario();
            dataCliente[3] = totalClientes.get(i).getCelular();
            dataCliente[4] = totalClientes.get(i).getNumTotalSuscripciones();
            dtm.addRow(dataCliente);
        }
        jTableClientes.setModel(dtm);
    }
    
    private void llenarJTableClientes(ArrayList<Cliente> clientes){
        DefaultTableModel dtm = new DefaultTableModel();
        
        String[] cabecera = {"Código", "Nombre completo", "Nombre de usuario", "Celular", "Nº suscripciones"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataCliente = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < clientes.size(); i++) {
            dataCliente[0] = clientes.get(i).getClienteId();
            dataCliente[1] = clientes.get(i).getNombreCompleto();
            dataCliente[2] = clientes.get(i).getNombreUsuario();
            dataCliente[3] = clientes.get(i).getCelular();
            dataCliente[4] = clientes.get(i).getNumTotalSuscripciones();
            dtm.addRow(dataCliente);
        }
        jTableClientes.setModel(dtm);
    }
    
    private void establecerPorDefecto(){
        llenarJTableClientes();
    }
    
    public GUIReporteGeneralClientes() {
        initComponents();
        establecerPorDefecto();
        configurarEncabezadoJTable();
        configurarRadioButtonOrden();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupOrdenar = new javax.swing.ButtonGroup();
        jPaneActualizar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rdbtnCantidadAscendente = new javax.swing.JRadioButton();
        rdbtnCantidadDescendente = new javax.swing.JRadioButton();
        rdbtnNombreAscendente = new javax.swing.JRadioButton();
        rdbtnNombreDescendente = new javax.swing.JRadioButton();

        jPaneActualizar.setBackground(new java.awt.Color(111, 159, 195));
        jPaneActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reporte general clientes");
        jPaneActualizar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 620, -1));

        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPaneActualizar.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 140, 50));

        btnExportar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnExportar.setText("Exportar");
        btnExportar.setEnabled(false);
        jPaneActualizar.add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 140, 50));

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableClientes.setFocusable(false);
        jTableClientes.setGridColor(new java.awt.Color(0, 0, 0));
        jTableClientes.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableClientes.setRowHeight(20);
        jTableClientes.setShowGrid(true);
        jScrollPane1.setViewportView(jTableClientes);

        jPaneActualizar.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 770, 250));

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Ordenar por:");
        jPaneActualizar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, -1));

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Nombre de cliente:");
        jPaneActualizar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 190, -1));

        jLabel12.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Cantidad de suscripciones:");
        jPaneActualizar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 190, -1));

        rdbtnCantidadAscendente.setBackground(new java.awt.Color(111, 159, 195));
        rdbtnCantidadAscendente.setText("Ascendente");
        rdbtnCantidadAscendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnCantidadAscendenteActionPerformed(evt);
            }
        });
        jPaneActualizar.add(rdbtnCantidadAscendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        rdbtnCantidadDescendente.setBackground(new java.awt.Color(111, 159, 195));
        rdbtnCantidadDescendente.setText("Descendente");
        rdbtnCantidadDescendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnCantidadDescendenteActionPerformed(evt);
            }
        });
        jPaneActualizar.add(rdbtnCantidadDescendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        rdbtnNombreAscendente.setBackground(new java.awt.Color(111, 159, 195));
        rdbtnNombreAscendente.setText("Ascendente");
        rdbtnNombreAscendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnNombreAscendenteActionPerformed(evt);
            }
        });
        jPaneActualizar.add(rdbtnNombreAscendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        rdbtnNombreDescendente.setBackground(new java.awt.Color(111, 159, 195));
        rdbtnNombreDescendente.setText("Descendente");
        rdbtnNombreDescendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnNombreDescendenteActionPerformed(evt);
            }
        });
        jPaneActualizar.add(rdbtnNombreDescendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void rdbtnNombreAscendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnNombreAscendenteActionPerformed
        // TODO add your handling code here:
        if(rdbtnNombreAscendente.isSelected()){
            totalClientes = controlador.ordenarClientesXNombresAsc(totalClientes);
            llenarJTableClientes(totalClientes);
        }
    }//GEN-LAST:event_rdbtnNombreAscendenteActionPerformed

    private void rdbtnNombreDescendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnNombreDescendenteActionPerformed
        // TODO add your handling code here:
        if(rdbtnNombreDescendente.isSelected()){
            totalClientes = controlador.ordenarClientesXNombresDesc(totalClientes);
            llenarJTableClientes(totalClientes);
        }
    }//GEN-LAST:event_rdbtnNombreDescendenteActionPerformed

    private void rdbtnCantidadAscendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnCantidadAscendenteActionPerformed
        // TODO add your handling code here:
        if(rdbtnCantidadAscendente.isSelected()){
            totalClientes = controlador.ordenarClientesXCantSuscripcionesAsc(totalClientes);
            llenarJTableClientes(totalClientes);
        }
    }//GEN-LAST:event_rdbtnCantidadAscendenteActionPerformed

    private void rdbtnCantidadDescendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnCantidadDescendenteActionPerformed
        // TODO add your handling code here:
        if(rdbtnCantidadDescendente.isSelected()){
            totalClientes = controlador.ordenarClientesXCantSuscripcionesDesc(totalClientes);
            llenarJTableClientes(totalClientes);
        }
    }//GEN-LAST:event_rdbtnCantidadDescendenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.ButtonGroup btnGroupOrdenar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPaneActualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JRadioButton rdbtnCantidadAscendente;
    private javax.swing.JRadioButton rdbtnCantidadDescendente;
    private javax.swing.JRadioButton rdbtnNombreAscendente;
    private javax.swing.JRadioButton rdbtnNombreDescendente;
    // End of variables declaration//GEN-END:variables
}
