/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.moduloServicioStreaming;

import vistas.moduloCliente.*;
import controladores.ControladorCliente;
import controladores.*;
import entidades.*;
import excepcionesPropias.DatoNoValido;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexander
 */
public class GUIActualizarServicioStreaming extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIRegistrar
     */
    ControladorServicioStreaming controlador = new ControladorServicioStreaming();
    
    private void limpiar(){
        txtBusquedaPlataforma.setText("");
        lblCodigo.setText("");
        txtCantMaxUsuarios.setText("");
        txtNombre.setText("");
    }
    
    private void configurarEncabezadoJTable(){
        jTablePlataformas.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 14));
        jTablePlataformas.getTableHeader().setOpaque(false);
        jTablePlataformas.getTableHeader().setForeground(Color.BLACK);
        
    }
    
    private void llenarJTablePlataformas(){
        DefaultTableModel dtm = new DefaultTableModel();
        
        ArrayList<TipoServicioStreaming> plataformas = new ArrayList<>();
        
        try {
            plataformas = controlador.obtenerServiciosStreaming();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un problema al cargar los datos de plataformas.");
        }
        
        String[] cabecera = {"Código", "Nombre de la plataforma", "Límite de usuarios"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataServiciosStreaming = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < plataformas.size(); i++) {
            dataServiciosStreaming[0] = plataformas.get(i).getTipoServicioId();
            dataServiciosStreaming[1] = plataformas.get(i).getNombre();
            dataServiciosStreaming[2] = plataformas.get(i).getMaxUsuarios();
            dtm.addRow(dataServiciosStreaming);
        }
        jTablePlataformas.setModel(dtm);
    }
    
    private void llenarJTablePlataformas(ArrayList<TipoServicioStreaming> plataformas){
        DefaultTableModel dtm = new DefaultTableModel();
        
        String[] cabecera = {"Código", "Nombre de la plataforma", "Límite de usuarios"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataServiciosStreaming = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < plataformas.size(); i++) {
            dataServiciosStreaming[0] = plataformas.get(i).getTipoServicioId();
            dataServiciosStreaming[1] = plataformas.get(i).getNombre();
            dataServiciosStreaming[2] = plataformas.get(i).getMaxUsuarios();
            dtm.addRow(dataServiciosStreaming);
        }
        jTablePlataformas.setModel(dtm);
    }
    
    private void establecerPorDefecto(){
        //cargarCodigo();
        limpiar();
        txtBusquedaPlataforma.setFocusable(true);
        llenarJTablePlataformas();
    }
    
    public GUIActualizarServicioStreaming() {
        initComponents();
        establecerPorDefecto();
        configurarEncabezadoJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneActualizar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBusquedaPlataforma = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCantMaxUsuarios = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlataformas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();

        jPaneActualizar.setBackground(new java.awt.Color(255, 255, 153));
        jPaneActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("streaming");
        jPaneActualizar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 60, 330, -1));

        lblCodigo.setBackground(new java.awt.Color(204, 204, 204));
        lblCodigo.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCodigo.setOpaque(true);
        jPaneActualizar.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 210, 20));

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cantidad máxima usuarios:");
        jPaneActualizar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 210, -1));

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Datos de plataforma de streaming:");
        jPaneActualizar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 240, -1));

        txtBusquedaPlataforma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaPlataformaKeyPressed(evt);
            }
        });
        jPaneActualizar.add(txtBusquedaPlataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 250, -1));

        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPaneActualizar.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 140, 50));

        btnActualizar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        jPaneActualizar.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 140, 50));

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Código:");
        jPaneActualizar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 210, -1));
        jPaneActualizar.add(txtCantMaxUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 280, -1));

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Buscar nombre de la plataforma streaming:");
        jPaneActualizar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 290, -1));

        jTablePlataformas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePlataformas.setFocusable(false);
        jTablePlataformas.setGridColor(new java.awt.Color(0, 0, 0));
        jTablePlataformas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTablePlataformas.setRowHeight(20);
        jTablePlataformas.setShowGrid(true);
        jTablePlataformas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePlataformasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePlataformas);

        jPaneActualizar.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 780, 190));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Actualización de plataforma");
        jPaneActualizar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nombre de la plataforma:");
        jPaneActualizar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 210, -1));
        jPaneActualizar.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        // TODO add your handling code here:
        try {
            if(lblCodigo.getText().equals("")){
                throw new DatoNoValido("Debe seleccionar una fila de la tabla.");
            }
            
            TipoServicioStreaming objTipoServicioStreaming = new TipoServicioStreaming();

            objTipoServicioStreaming.setTipoServicioId(Integer.parseInt(lblCodigo.getText()));
            objTipoServicioStreaming.setNombre(txtNombre.getText().trim());
            objTipoServicioStreaming.setMaxUsuarios(Integer.parseInt(txtCantMaxUsuarios.getText().trim()));

            controlador.actualizarTipoServicio(objTipoServicioStreaming);

            JOptionPane.showMessageDialog(this, String.format("Datos del servicio streaming %s actualizados correctamente.", objTipoServicioStreaming.getNombre()));

            establecerPorDefecto();
        } catch (DatoNoValido | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error. Intente nuevamente.");
        }
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void jTablePlataformasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePlataformasMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = 0;
        
        if(jTablePlataformas.getSelectedRow() != -1){
            filaSeleccionada = jTablePlataformas.getSelectedRow();
            lblCodigo.setText(jTablePlataformas.getValueAt(filaSeleccionada, 0) + "");
            txtNombre.setText(jTablePlataformas.getValueAt(filaSeleccionada, 1) + "");
            txtCantMaxUsuarios.setText(jTablePlataformas.getValueAt(filaSeleccionada, 2) + "");
        }
    }//GEN-LAST:event_jTablePlataformasMouseClicked

    private void txtBusquedaPlataformaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaPlataformaKeyPressed
        // TODO add your handling code here:

        try {
            llenarJTablePlataformas(controlador.obtenerServiciosStreaming(txtBusquedaPlataforma.getText().trim()));
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_txtBusquedaPlataformaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPaneActualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePlataformas;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTextField txtBusquedaPlataforma;
    private javax.swing.JTextField txtCantMaxUsuarios;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
