/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.moduloServicioStreaming;

import vistas.moduloCliente.*;
import controladores.*;
import entidades.*;
import excepcionesPropias.DatoNoValido;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexander
 */
public class GUIEliminacionServicioStreaming extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIRegistrar
     */
    ControladorServicioStreaming controlador = new ControladorServicioStreaming();
    TipoServicioStreaming servicioStreamingPorEliminar = new TipoServicioStreaming();
    
    private void limpiar(){
        txtBusquedaPlataforma.setText("");
    }
    
    private void configurarEncabezadoJTable(){
        jTablePlataformas.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 14));
        jTablePlataformas.getTableHeader().setOpaque(false);
        jTablePlataformas.getTableHeader().setForeground(Color.BLACK);
        
    }
    
    private void llenarJTablePlataformas(){
        DefaultTableModel dtm = new DefaultTableModel();
        
        ArrayList<TipoServicioStreaming> plataformas = new ArrayList<>();
        
        try {
            plataformas = controlador.obtenerServiciosStreaming();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un problema al cargar los datos.");
        }
        
        String[] cabecera = {"Código", "Nombre de la plataforma", "Límite de usuarios"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataPlataformas = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < plataformas.size(); i++) {
            dataPlataformas[0] = plataformas.get(i).getTipoServicioId();
            dataPlataformas[1] = plataformas.get(i).getNombre();
            dataPlataformas[2] = plataformas.get(i).getMaxUsuarios();
            dtm.addRow(dataPlataformas);
        }
        jTablePlataformas.setModel(dtm);
    }
    
    private void llenarJTablePlataformas(ArrayList<TipoServicioStreaming> plataformas){
        DefaultTableModel dtm = new DefaultTableModel();
        
        String[] cabecera = {"Código", "Nombre de plataforma", "Cantidad máxima de usuarios"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataPlataformas = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < plataformas.size(); i++) {
            dataPlataformas[0] = plataformas.get(i).getTipoServicioId();
            dataPlataformas[1] = plataformas.get(i).getNombre();
            dataPlataformas[2] = plataformas.get(i).getMaxUsuarios();
            dtm.addRow(dataPlataformas);
        }
        jTablePlataformas.setModel(dtm);
    }
    
    private void establecerPorDefecto(){
        //cargarCodigo();
        limpiar();
        txtBusquedaPlataforma.setFocusable(true);
        llenarJTablePlataformas();
    }
    
    public GUIEliminacionServicioStreaming() {
        initComponents();
        establecerPorDefecto();
        configurarEncabezadoJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneActualizar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBusquedaPlataforma = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlataformas = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 153));

        jPaneActualizar.setBackground(new java.awt.Color(255, 255, 153));
        jPaneActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eliminación de plataformas");
        jPaneActualizar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 700, -1));

        txtBusquedaPlataforma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaPlataformaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaPlataformaKeyTyped(evt);
            }
        });
        jPaneActualizar.add(txtBusquedaPlataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 280, -1));

        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPaneActualizar.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 140, 50));

        btnEliminar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        jPaneActualizar.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 140, 50));

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Buscar nombre de servicio de streaming:");
        jPaneActualizar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 280, -1));

        jTablePlataformas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePlataformas.setFocusable(false);
        jTablePlataformas.setGridColor(new java.awt.Color(0, 0, 0));
        jTablePlataformas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTablePlataformas.setRowHeight(20);
        jTablePlataformas.setShowGrid(true);
        jTablePlataformas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePlataformasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePlataformas);

        jPaneActualizar.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 770, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        try {
            if(servicioStreamingPorEliminar.getTipoServicioId() == 0){
                throw new DatoNoValido("Debe seleccionar una fila de la tabla.");
            }
            controlador.eliminarTipoServicio(servicioStreamingPorEliminar);

            JOptionPane.showMessageDialog(this, String.format("Datos de la plataforma %s eliminados correctamente.", servicioStreamingPorEliminar.getNombre()));

            establecerPorDefecto();
        } catch (DatoNoValido | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void txtBusquedaPlataformaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaPlataformaKeyPressed
        // TODO add your handling code here:
        
        try {
            llenarJTablePlataformas(controlador.obtenerServiciosStreaming(txtBusquedaPlataforma.getText().trim()));
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_txtBusquedaPlataformaKeyPressed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void txtBusquedaPlataformaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaPlataformaKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtBusquedaPlataformaKeyTyped

    private void jTablePlataformasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePlataformasMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = 0;
        
        if(jTablePlataformas.getSelectedRow() != -1){
            filaSeleccionada = jTablePlataformas.getSelectedRow();
            
            //Solo el código
            servicioStreamingPorEliminar.setTipoServicioId(Integer.parseInt(jTablePlataformas.getValueAt(filaSeleccionada, 0) + ""));
            servicioStreamingPorEliminar.setNombre(jTablePlataformas.getValueAt(filaSeleccionada, 1) + "");
        }
    }//GEN-LAST:event_jTablePlataformasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPaneActualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePlataformas;
    private javax.swing.JTextField txtBusquedaPlataforma;
    // End of variables declaration//GEN-END:variables
}
