/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.moduloServicioStreaming;

import controladores.*;
import entidades.*;
import excepcionesPropias.DatoNoValido;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexander
 */
public class GUIGenerarPlan extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIRegistrar
     */
    
    private void cargarCodigo(){
        ControladorServicioStreaming controlador = new ControladorServicioStreaming();
        try {
            lblCodigo.setText(controlador.obtenerNuevoCodigoPlan()+ "");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void limpiar(){
        txtTiempoSuscripcion.setText("");
        txtCosto.setText("");
    }
    
    private void cargarCboPlataformas(){
        ControladorServicioStreaming controlador = new ControladorServicioStreaming();
        ArrayList<TipoServicioStreaming> plataformas;
        try {
            plataformas = controlador.obtenerServiciosStreaming();
            plataformas = controlador.ordenarTipoServiciosXNombreAsc(plataformas);
            for (int i = 0; i < plataformas.size(); i++) {
                cboPlataformas.addItem(plataformas.get(i).getTipoServicioId() + " - " + plataformas.get(i).getNombre());
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUIGenerarPlan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void establecerPorDefecto(){
        cargarCodigo();
        cargarCboPlataformas();
        limpiar();
        txtTiempoSuscripcion.setFocusable(true);
    }
    
    public GUIGenerarPlan() {
        initComponents();
        establecerPorDefecto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneRegistrarPlan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTiempoSuscripcion = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cboPlataformas = new javax.swing.JComboBox<>();

        jPaneRegistrarPlan.setBackground(new java.awt.Color(255, 255, 153));
        jPaneRegistrarPlan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generar plan de servicio");
        jPaneRegistrarPlan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 680, -1));

        lblCodigo.setBackground(new java.awt.Color(204, 204, 204));
        lblCodigo.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCodigo.setOpaque(true);
        jPaneRegistrarPlan.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 180, 20));

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Tiempo de suscripcion en meses:");
        jPaneRegistrarPlan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 250, -1));

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Costo:");
        jPaneRegistrarPlan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 210, -1));

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Seleccionar plataforma de streaming:");
        jPaneRegistrarPlan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 260, -1));
        jPaneRegistrarPlan.add(txtTiempoSuscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 280, -1));
        jPaneRegistrarPlan.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 280, -1));

        btnRegistrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        jPaneRegistrarPlan.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 140, 50));

        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPaneRegistrarPlan.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 140, 50));

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Código (autogenerado) :");
        jPaneRegistrarPlan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 210, -1));
        jPaneRegistrarPlan.add(cboPlataformas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneRegistrarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneRegistrarPlan, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
        try {
            if(txtTiempoSuscripcion.getText().equals("") || txtCosto.getText().equals("")){
                throw new DatoNoValido("Debe ingresar datos en todos los campos.");
            }
            
            Plan objPlan = new Plan();
            ControladorServicioStreaming controlador = new ControladorServicioStreaming();

            String item[] = cboPlataformas.getSelectedItem().toString().split("-");
            
            objPlan.setTipoServicioId(Integer.parseInt(item[0].trim()));
            objPlan.setTiempoMeses(Integer.parseInt(txtTiempoSuscripcion.getText()));
            objPlan.setCosto(Double.parseDouble(txtCosto.getText()));

            controlador.generarPlan(objPlan);

            JOptionPane.showMessageDialog(this, "Nuevo plan registrado al sistema.");

            establecerPorDefecto();
        } catch (DatoNoValido | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Asegúrese de colocar datos correctamente.");
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboPlataformas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPaneRegistrarPlan;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtTiempoSuscripcion;
    // End of variables declaration//GEN-END:variables
}
