/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.moduloServicioStreaming;

import vistas.moduloCliente.*;
import controladores.ControladorCliente;
import controladores.ControladorServicioStreaming;
import entidades.Cliente;
import entidades.TipoServicioStreaming;
import excepcionesPropias.DatoNoValido;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexander
 */
public class GUIReporteServiciosStreaming extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIRegistrar
     */
    ControladorServicioStreaming controlador = new ControladorServicioStreaming();
    ArrayList<TipoServicioStreaming> totalPlataformas;
    
    private void configurarRadioButtonOrden(){
        btnGroupOrdenar.add(rdbtnNombreAscendente);
        btnGroupOrdenar.add(rdbtnNombreDescendente);
    }
    
    private void configurarEncabezadoJTable(){
        jTablePlataformas.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 14));
        jTablePlataformas.getTableHeader().setOpaque(false);
        jTablePlataformas.getTableHeader().setForeground(Color.BLACK);
        
    }
    
    private void llenarJTablePlataformas(){
        DefaultTableModel dtm = new DefaultTableModel();
        
        try {
            totalPlataformas = controlador.obtenerServiciosStreaming();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un problema al cargar los datos.");
        }
        
        String[] cabecera = {"Código", "Nombre de la plataforma", "Límite de usuarios por cuenta asociada"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataPlataforma = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < totalPlataformas.size(); i++) {
            dataPlataforma[0] = totalPlataformas.get(i).getTipoServicioId();
            dataPlataforma[1] = totalPlataformas.get(i).getNombre();
            dataPlataforma[2] = totalPlataformas.get(i).getMaxUsuarios();
            dtm.addRow(dataPlataforma);
        }
        jTablePlataformas.setModel(dtm);
    }
    
    private void llenarJTablePlataformas(ArrayList<TipoServicioStreaming> plataformas){
        DefaultTableModel dtm = new DefaultTableModel();
        
        String[] cabecera = {"Código", "Nombre de la plataforma", "Límite de usuarios por cuenta asociada"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataPlataforma = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < totalPlataformas.size(); i++) {
            dataPlataforma[0] = totalPlataformas.get(i).getTipoServicioId();
            dataPlataforma[1] = totalPlataformas.get(i).getNombre();
            dataPlataforma[2] = totalPlataformas.get(i).getMaxUsuarios();
            dtm.addRow(dataPlataforma);
        }
        jTablePlataformas.setModel(dtm);
    }
    
    private void establecerPorDefecto(){
        llenarJTablePlataformas();
    }
    
    public GUIReporteServiciosStreaming() {
        initComponents();
        establecerPorDefecto();
        configurarEncabezadoJTable();
        configurarRadioButtonOrden();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupOrdenar = new javax.swing.ButtonGroup();
        jPaneReporte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlataformas = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rdbtnNombreAscendente = new javax.swing.JRadioButton();
        rdbtnNombreDescendente = new javax.swing.JRadioButton();

        jPaneReporte.setBackground(new java.awt.Color(255, 255, 153));
        jPaneReporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reporte servicios streaming");
        jPaneReporte.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 760, -1));

        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPaneReporte.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 140, 50));

        jTablePlataformas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePlataformas.setFocusable(false);
        jTablePlataformas.setGridColor(new java.awt.Color(0, 0, 0));
        jTablePlataformas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTablePlataformas.setRowHeight(20);
        jTablePlataformas.setShowGrid(true);
        jScrollPane1.setViewportView(jTablePlataformas);

        jPaneReporte.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 770, 290));

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Ordenar por:");
        jPaneReporte.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, -1));

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Nombre de plataforma streaming:");
        jPaneReporte.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 110, 240, -1));

        rdbtnNombreAscendente.setBackground(new java.awt.Color(255, 255, 153));
        rdbtnNombreAscendente.setText("Ascendente");
        rdbtnNombreAscendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnNombreAscendenteActionPerformed(evt);
            }
        });
        jPaneReporte.add(rdbtnNombreAscendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        rdbtnNombreDescendente.setBackground(new java.awt.Color(255, 255, 153));
        rdbtnNombreDescendente.setText("Descendente");
        rdbtnNombreDescendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnNombreDescendenteActionPerformed(evt);
            }
        });
        jPaneReporte.add(rdbtnNombreDescendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void rdbtnNombreAscendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnNombreAscendenteActionPerformed
        // TODO add your handling code here:
        if(rdbtnNombreAscendente.isSelected()){
            totalPlataformas = controlador.ordenarTipoServiciosXNombreAsc(totalPlataformas);
            llenarJTablePlataformas(totalPlataformas);
        }
    }//GEN-LAST:event_rdbtnNombreAscendenteActionPerformed

    private void rdbtnNombreDescendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnNombreDescendenteActionPerformed
        // TODO add your handling code here:
        if(rdbtnNombreDescendente.isSelected()){
            totalPlataformas = controlador.ordenarTipoServiciosXNombreDesc(totalPlataformas);
            llenarJTablePlataformas(totalPlataformas);
        }
    }//GEN-LAST:event_rdbtnNombreDescendenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupOrdenar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPaneReporte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePlataformas;
    private javax.swing.JRadioButton rdbtnNombreAscendente;
    private javax.swing.JRadioButton rdbtnNombreDescendente;
    // End of variables declaration//GEN-END:variables
}
