/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.moduloServicioStreaming;

import vistas.moduloCliente.*;
import controladores.*;
import entidades.*;
import excepcionesPropias.DatoNoValido;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexander
 */
public class GUIRegistrarServicioStreaming extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIRegistrar
     */
    
    private void cargarCodigo(){
        ControladorServicioStreaming controlador = new ControladorServicioStreaming();
        try {
            lblCodigo.setText(controlador.obtenerNuevoCodigo()+ "");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void limpiar(){
        txtNombre.setText("");
        txtCantidadMaxima.setText("");
    }
    
    private void establecerPorDefecto(){
        cargarCodigo();
        limpiar();
        txtNombre.setFocusable(true);
    }
    
    public GUIRegistrarServicioStreaming() {
        initComponents();
        establecerPorDefecto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneRegistrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCantidadMaxima = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jPaneRegistrar.setBackground(new java.awt.Color(255, 255, 153));
        jPaneRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de servicio streaming");
        jPaneRegistrar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 790, -1));

        lblCodigo.setBackground(new java.awt.Color(204, 204, 204));
        lblCodigo.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCodigo.setOpaque(true);
        jPaneRegistrar.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 210, 20));

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nombre:");
        jPaneRegistrar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 210, -1));

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Cantidad máxima de usuarios:");
        jPaneRegistrar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 210, -1));

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Código (autogenerado) :");
        jPaneRegistrar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 210, -1));
        jPaneRegistrar.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 280, -1));
        jPaneRegistrar.add(txtCantidadMaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 280, -1));

        btnRegistrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        jPaneRegistrar.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 140, 50));

        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPaneRegistrar.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
        try {
            if(txtNombre.getText().equals("") || txtCantidadMaxima.getText().equals("")){
                throw new DatoNoValido("Debe ingresar datos en todos los campos.");
            }
            
            TipoServicioStreaming objTipoServicioStreaming = new TipoServicioStreaming();
            ControladorServicioStreaming controlador = new ControladorServicioStreaming();

            objTipoServicioStreaming.setNombre(txtNombre.getText().trim());
            objTipoServicioStreaming.setMaxUsuarios(Integer.parseInt(txtCantidadMaxima.getText().trim()));

            controlador.registrarTipoServicio(objTipoServicioStreaming);

            JOptionPane.showMessageDialog(this, String.format("Nuevo servicio %s registrado exitosamente", objTipoServicioStreaming.getNombre()));

            establecerPorDefecto();
        } catch (DatoNoValido | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Asegúrese de colocar un número entero en el campo 'Cantidad máxima de usuarios'.");
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPaneRegistrar;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTextField txtCantidadMaxima;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
